const express = require('express');
const router = express.Router();
const verifyJWT = require('../middleware/verifyJWT');
const {createAlumno} = require('../controllers/userController');
const { loginAlumno } = require('../controllers/userController');
const {updateAlumno} = require('../controllers/userController');
const { updateAlumnoPatch } = require('../controllers/userController');
const { getAlumnoByDni } = require('../controllers/userController');
const { deleteAlumno } = require('../controllers/userController');
const { getCursosByAlumno } = require('../controllers/userController');
const { cancelarInscripcionCurso } = require('../controllers/userController');
const { getTalleresByAlumno } = require('../controllers/userController');
const { inscribirAlumnoEnCurso } = require('../controllers/userController');
const { inscribirAlumnoEnTaller } = require('../controllers/userController');
const { cancelarInscripcionTaller } = require('../controllers/userController');

router.post('/login', loginAlumno);
router.post('/alumno', createAlumno);
router.put('/alumno/:dni', verifyJWT, updateAlumno);
router.patch('/alumno/:dni', verifyJWT, updateAlumnoPatch);
router.get('/alumno/:dni', verifyJWT, getAlumnoByDni);
router.delete('/alumno/:dni', verifyJWT, deleteAlumno);
router.get('/alumno/:dni/cursos', verifyJWT, getCursosByAlumno);
router.patch('/inscripcion_curso/:dni/:idcurso', verifyJWT, cancelarInscripcionCurso);
router.get('/alumno/:dni/talleres', verifyJWT, getTalleresByAlumno);
router.post('/inscripcion_curso', verifyJWT, inscribirAlumnoEnCurso);
router.post('/inscripcion_taller', verifyJWT, inscribirAlumnoEnTaller);
router.patch('/inscripcion_taller/:dni/:idtaller', verifyJWT, cancelarInscripcionTaller);
module.exports = router;