const express = require('express');
const router = express.Router();
const {createAlumno} = require('../controllers/userController');
const { loginAlumno } = require('../controllers/userController');
const {updateAlumno} = require('../controllers/userController');
const { updateAlumnoPatch } = require('../controllers/userController');
const { getAlumnoByDni } = require('../controllers/userController');
const { deleteAlumno } = require('../controllers/userController');
const { getCursosByAlumno } = require('../controllers/userController');
const { cancelarInscripcionCurso } = require('../controllers/userController');
const { getTalleresByAlumno } = require('../controllers/userController');
const { inscribirAlumnoEnCurso } = require('../controllers/userController');
const { inscribirAlumnoEnTaller } = require('../controllers/userController');
const { cancelarInscripcionTaller } = require('../controllers/userController');

router.post('/login', loginAlumno);
router.post('/alumno', createAlumno);
router.put('/alumno/:dni', updateAlumno);
router.patch('/alumno/:dni', updateAlumnoPatch);
router.get('/alumno/:dni', getAlumnoByDni);
router.delete('/alumno/:dni', deleteAlumno);
router.get('/alumno/:dni/cursos', getCursosByAlumno);
router.patch('/inscripcion_curso/:dni/:idcurso', cancelarInscripcionCurso);
router.get('/alumno/:dni/talleres', getTalleresByAlumno);
router.post('/inscripcion_curso', inscribirAlumnoEnCurso);
router.post('/inscripcion_taller', inscribirAlumnoEnTaller);
router.patch('/inscripcion_taller/:dni/:idtaller', cancelarInscripcionTaller);
module.exports = router;